env = Environment()


######
# libinface-python.so
######
import distutils.sysconfig, os
vars = distutils.sysconfig.get_config_vars('CC', 'CXX', 'OPT', \
                        'BASECFLAGS', 'CCSHARED', 'LDSHARED', 'SO')
for i in range(len(vars)):
    if vars[i] is None:
        vars[i] = ""
(cc, cxx, opt, basecflags, ccshared, ldshared, so_ext) = vars

env.ParseConfig("pkg-config --cflags --libs libaltsvg")
env.ParseConfig("pkg-config --cflags --libs xext")

env.AppendUnique(CPPPATH=[distutils.sysconfig.get_python_inc()])

env.AppendUnique(CFLAGS=['-g'])
env.AppendUnique(CFLAGS=['-Isrc/lib'])

lib = env.SharedLibrary(target='inkface',
                source=['inkface.c','#src/lib/common.c'])

if type(lib) == type([]): lib = lib[0]

env.Command('inkface.so','libinkface.so',
            [
                Move("$TARGET","$SOURCE"),
            ])
