

env = Environment()
conf = Configure(env)
if not conf.CheckLib('altsvg'):
    print "Didn't find libaltsvg"
    Exit(1)
env = conf.Finish()

env.ParseConfig("pkg-config --cflags --libs libaltsvg")

env.SharedLibrary(target='inkface',
                source=['inkface.c'])
                
