

#if 'deb' in COMMAND_LINE_TARGETS:
#    SConscript(['debian/SConscript'])
#    Exit()

VERSION = '0.1.0'
ARCH = 'armel'
MAINTAINER = 'Jayesh Salvi <jayesh@altfrequency.com>'
DEPENDS = 'libaltsvg (>= 0.1.0)'
DESCRIPTION = 'UI framework based on SVG'
PKGNAME = 'inkface-python'

Export('VERSION ARCH MAINTAINER DEPENDS DESCRIPTION PKGNAME')

SConscript(['src/lib.sc','src/python.sc','debian/SConscript'])

